# Generated by Django 4.2 on 2023-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='post_logos/'),
        ),
    ]
