# Generated by Django 4.2 on 2023-08-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_app', '0004_post_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-creation_date']},
        ),
    ]
