# Generated by Django 4.2 on 2023-08-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_app', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
