# Generated by Django 4.2 on 2023-08-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_app', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_closed',
            field=models.IntegerField(default=False),
        ),
    ]
