# Generated by Django 4.2 on 2023-08-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_app', '0007_post_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
